version: "3"
services:
  postgres:
    image: postgres:14-alpine
    container_name: zilla-postgres
    restart: always
    ports:
      - "5450:5450"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=zilla
      - PGPORT=5450

  redis:
    image: redis:6.2-alpine
    container_name: zilla-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "password"]
    environment:
      - REDIS_DATABASES=1

  migrations:
    image: liquibase/liquibase:4.25-alpine
    container_name: zilla-migrations
    environment:
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=dbchangelog.xml
      - LIQUIBASE_COMMAND_UPDATE_URL=jdbc:postgresql://postgres:5450/zilla
      - LIQUIBASE_COMMAND_USERNAME=user
      - LIQUIBASE_COMMAND_PASSWORD=pass
      - LIQUIBASE_LOG_LEVEL=info
    volumes:
      - ./schema:/liquibase/changelog/
    command: "update --defaultSchemaName=public"
    depends_on:
      - postgres

  zilla-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: zilla-backend
    image: zilla-backend
    restart: always
    command: ["npm", "run", "start:prod"]
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5450
      - DB_NAME=zilla
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN_IN_SECONDS=100000
      - NODE_ENV=test
      - ADMIN_EMAL=urosvceh@gmail.com
      - ADMIN_PASSWORD=pass123!
    depends_on:
      - postgres
      - redis

  zilla-backend-pull:
    image: hatch33/zilla-backend:pull
    container_name: zilla-backend-pull
    restart: always
    command: ["npm", "run", "start:prod"]
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5450
      - DB_NAME=zilla
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN_IN_SECONDS=100000
      - NODE_ENV=test
      - ADMIN_EMAL=urosvceh@gmail.com
      - ADMIN_PASSWORD=pass123!
